apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: provisioners.karpenter.sh
spec:
  group: karpenter.sh
  scope: Cluster
  names:
    plural: provisioners
    singular: provisioner
    kind: Provisioner
    shortNames:
      - prov
  versions:
    - name: v1alpha5
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                requirements:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                      values:
                        type: array
                        items:
                          type: string
                limits:
                  type: object
                  properties:
                    resources:
                      type: object
                      additionalProperties:
                        type: string
                ttlSecondsAfterEmpty:
                  type: integer
            status:
              type: object
